package com.jdjz.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jdjz.db.Friend;
import com.jdjz.db.Country;
import com.jdjz.db.area;

import com.jdjz.db.FriendDao;
import com.jdjz.db.CountryDao;
import com.jdjz.db.areaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendDaoConfig;
    private final DaoConfig countryDaoConfig;
    private final DaoConfig areaDaoConfig;

    private final FriendDao friendDao;
    private final CountryDao countryDao;
    private final areaDao areaDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        countryDaoConfig = daoConfigMap.get(CountryDao.class).clone();
        countryDaoConfig.initIdentityScope(type);

        areaDaoConfig = daoConfigMap.get(areaDao.class).clone();
        areaDaoConfig.initIdentityScope(type);

        friendDao = new FriendDao(friendDaoConfig, this);
        countryDao = new CountryDao(countryDaoConfig, this);
        areaDao = new areaDao(areaDaoConfig, this);

        registerDao(Friend.class, friendDao);
        registerDao(Country.class, countryDao);
        registerDao(area.class, areaDao);
    }
    
    public void clear() {
        friendDaoConfig.clearIdentityScope();
        countryDaoConfig.clearIdentityScope();
        areaDaoConfig.clearIdentityScope();
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public CountryDao getCountryDao() {
        return countryDao;
    }

    public areaDao getAreaDao() {
        return areaDao;
    }

}
